services:

  postgres:
    image: postgres:16

    container_name: postgres-tree-db

    environment:
      POSTGRES_DB: plan_cuentas_tree_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docs/sql/schema-postgres.sql:/docker-entrypoint-initdb.d/schema-postgres.sql

  mongodb:
    image: mongo:latest

    container_name: tree-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: