server.port=8081

app.tree-strategy=collections
app.storage=mongo

spring.profiles.active=dynamic

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration